### PR TITLE
Create ChunkGenerator2D.lua

### PR DESCRIPTION
**Pull request by RedstonedLife**

### CODE REVIEW

**Comment by RedstonedLife** [comment]
Hey does anyone even check the pull requests XD?,

**Comment by RedstonedLife** [comment]
Or just add me to the collaborators.
tal.baskin1@gmail.com (If you do so i don't have to make pull requests god damn it)

**Comment by CLarramore** [comment]
I have fortunately dropped in because of this pull request i have recieved.

**Comment by quiloos39** [comment]
I am just not good at using github sorry for that guys. I will be trying to be more active.

**Review by quiloos39 — CHANGES_REQUESTED** [review]
If you add date it will be good to go.

**Pull request closed without merging**
